<%@ page language='java'  %>
<%@ page language='java' import='com.sbt.control.WebUtils'%>
<%@ page language='java' import='com.sbt.weixin.components.JsSdkConfig'%>
<%@ page language='java' import='com.sbt.mj.constants.WxMjConstants'%>
<%@ page language='java' import='com.sbt.mj.constants.WxMjActions'%>
<%@ page language='java' import='com.sbt.weixin.constants.WeiXinConstants'%>
<%@ page language='java' import='com.sbt.weixin.constants.WeiXinActions'%>
<%@ page language='java' import='com.sbt.constants.BasicActions'%>
<%@ page language='java' import='com.sbt.mj.constants.DyGamePosition'%>
<%@ page language='java' import='com.sbt.constants.StringConstants'%>
<%@ page language='java' import='com.sbt.control.GlobalVariables'%>
<%@ page language='java' import='com.sbt.control.impl.jsp.JspUtils'%>
<%@ page language='java' import='com.sbt.control.impl.jsp.JspResultContainer'%>
<%@ page language='java' import='com.sbt.control.impl.jsp.PageContent'%>
<%@ page language='java' import='com.sbt.mj.wxmj.WxMjUtils'%>
<%@ page language='java' import='com.sbt.mj.wxmj.WxMjConfig'%>
<%@ page language='java' import='com.sbt.mj.wxmj.view.*'%>
